AZURE_OPENAI_ENDPOINT = "https://anthonylui.openai.azure.com"
AZURE_OPENAI_API_KEY = "3707d10eab2b4368b73998b8802838de"
AZURE_OPENAI_DEPLOYMENT_NAME = "o1-preview-2"
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = "text-embedding-ada-002"
AZURE_OPENAI_API_VERSION = "2024-05-01-preview"

NEO4J_URI = "neo4j+s://5a50d911.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "izmc4aXhUOjjrm2-6HC3VT09HkadNA-nwAmZVqZzvAE"
